### ISSUE TITLE
Script to send automatic invites to local group broadcasts

### ISSUE THREAD

**Issue by SamLubbers** [xrnl/rebel_management_utilities#17]
1. Get new signups from Action Network
2. If they have a municipality, map their municipality to a local group
3. if that local group has a broadcast, send them a message on Telegram welcoming them to XR + inviting them to the telegram broadcast of their local group using a link

some additional thoughts:

1. what do we do when a new local group creates a broadcast? Should we implement a functionality to automatically invite people in that area to the broadcast?
2. maybe it's an idea to use a dedicated XR NL Telegram broadcast account?

**Comment by martijnmartijnmartijnmartijn** [comment]
About your additional points:
1. I thought our plan was that local group integrators would send their broadcast to us when they made it, so that we could add it to our list which is automatically taken along in this script. So yes I think we should do that. 
2. This is a great idea. I had a script running through my personal account for a while, and my telegram was completely spammed, as the script sent messages to about 5 people a day. We do need a phone number to set this up though, I think.
